### ISSUE TITLE
Apply your model on custom longer video clips

### ISSUE THREAD

**Issue by fabiozappo** [rozumden/DeFMO#2]
Hi thank you for releasing your code, 

Can your model be applied on custom videos about high speed train crossing? Video clips last from 3 to 10 seconds, my idea was to preprocess them with your code in order to keep the same frame rate and have a better video quality for later object detection. This is an example frame from original video clip:

![vlcsnap-2021-05-25-15h27m32s030](https://user-images.githubusercontent.com/46443190/119505952-bf176b00-bd6d-11eb-96a0-78f7ad4a5d04.png)

I tried to run your code on a video about 6 seconds and the result was a longer video (about 13min) with a lower level of detail, probably I'm doing something wrong. This is an example frame from output video clip: 

![vlcsnap-2021-05-25-15h26m22s237](https://user-images.githubusercontent.com/46443190/119505764-955e4400-bd6d-11eb-9f04-3638f60767af.png)

How can I correctly reconstruct the quality of single frames usin all the information contained in the video?

**Comment by rozumden** [comment]
Hi Fabio,

It can be applied. The main goal of DeFMO is to increase the frame rate from a low frame rate video. So the result will always be a longer video. If your goal is to keep the same frame rate and have a better video quality, you could try standard image deblurring methods. 

Alternatively, you can use DeFMO to generate the same frame rate video but with lower exposure time, e.g. by evaluating the rendering network only at time step 0.5 for each frame separately. This should improve the quality.

Also, your video clips are quite challenging due to shaking/moving camera and also obstacles (tree in front of the train). I'd suggest applying some deblurring method to remove the sharing camera blur first. Then, the DeFMO output might also improve. Currently, DeFMO can't deal with obstacles, unfortunately.

Best regards,
Denys

**Comment by mpourkeshavarz** [comment]
@fabiozappo did you find any useful approach? I have the same problem as yours

**Comment by rozumden** [comment]
> @fabiozappo did you find any useful approach? I have the same problem as yours

Hi Mozhgan, could you please share your input data? I can take a look at it and let you know what is the problem. Best, Denys

**Comment by mpourkeshavarz** [comment]
@fabiozappo many thanks for your prompt reply,
these are 2 samples (one blurry frame from my video), The cropped one is the main one but I have the whole scene if it could help for improving frame quality. (I need to improve the video quality for later object detection.)
![2020 03 01 rma_deu_first_00002 dat_fr_0375_odd_bb_vis](https://user-images.githubusercontent.com/36272225/149381980-0fc85eb8-a920-44af-a54d-4ecd5deb7457.png)
![2020 03 01 rma_deu_first_00002 dat_fr_0375_odd_vis](https://user-images.githubusercontent.com/36272225/149381983-44130dd7-40c4-4f35-99c9-e06637fcf007.png)
